ALTER DATABASE `ilya_SledgePlus` CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `Group` CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `Lessons` CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `Roles` CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `Sections` CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `Users` CONVERT TO CHARACTER SET utf8 COLLATE utf8_unicode_ci;